### ISSUE TITLE
run_release should regenerate configure after editing configure.ac.

### ISSUE THREAD

**Issue by Yhg1s** [python/release-tools#126] opened 2024-05-08 15:27 UTC
As part of the release process for beta 1, run_release edits (or makes the user edit, rather) in `main` various files to replace the just-released version with the next major version. One of the files that needs to be changed is `configure.ac`, but run_release doesn't then regenerate the configure script, causing all builds to fail when pushed to github.

**Comment by Yhg1s** [comment] 2024-05-08 15:35
There's also a couple of files that need editing for Windows: https://github.com/python/cpython/pull/118766

**Comment by Eclips4** [comment] 2024-05-08 16:58
Looks like a duplicate of #45

**Closed** 2024-05-10 11:48 UTC
